spring.application.name=Thymeleaf-Demo

# database config changed to file persistence
spring.datasource.url=jdbc:h2:file:./data/tekken
# default credentials
spring.datasource.username=chris
spring.datasource.password=root
spring.datasource.driverClassName=org.h2.Driver

# the jpa config changed from create-drop to update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

# h2 console for debugging
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# for the sql init
spring.sql.init.mode=always